'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ClipboardList, RefreshCw, Plus, Save } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { money, type Product } from '@/lib/catalog';

type Order={id:string;code:string;customerName:string;phone:string;fulfillment:string;address:string;note:string;subtotal:number;deliveryFee:number;total:number;paidAmount:number;paymentMethod:string;paymentStatus:string;status:string;createdAt:string;items:{name:string;quantity:number;price:number}[]};
type AdminProduct=Product&{active:boolean;updatedAt:string};
type Zone={id:string;name:string;fee:number;active:boolean};
type StoreSettings={ordersEnabled:boolean;pickupEnabled:boolean;deliveryEnabled:boolean;payOnPickupEnabled:boolean;pixEnabled:boolean};
const states:Record<string,string>={test:'Teste',awaiting_payment:'Aguardando Pix',received:'Recebido',preparing:'Preparando',out_for_delivery:'Saiu para entrega',complete:'Concluído',cancelled:'Cancelado'};
const blankProduct:AdminProduct={id:'',name:'',description:'',category:'Esfirras salgadas',price:600,active:true,updatedAt:''};
export default function Admin(){
  const [orders,setOrders]=useState<Order[]>([]),[products,setProducts]=useState<AdminProduct[]>([]),[zones,setZones]=useState<Zone[]>([]);
  const [settings,setSettings]=useState<StoreSettings>({ordersEnabled:false,pickupEnabled:true,deliveryEnabled:false,payOnPickupEnabled:false,pixEnabled:false});
  const [pixConfigured,setPixConfigured]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState('');
  const [editing,setEditing]=useState<AdminProduct|null>(null),[zoneDraft,setZoneDraft]=useState<Zone>({id:'',name:'',fee:0,active:true});
  const [amounts,setAmounts]=useState<Record<string,string>>({});
  const [productPrice,setProductPrice]=useState('6.00'),[zoneFee,setZoneFee]=useState('0.00');
  const readJson=async(response:Response)=>{const data=await response.json() as Record<string,unknown>;if(!response.ok)throw new Error(String(data.error??'Ação indisponível.'));return data;};
  const load=useCallback(async()=>{try{const [o,p,s]=await Promise.all(['/api/admin/orders','/api/admin/catalog','/api/admin/settings'].map(url=>fetch(url,{cache:'no-store'}).then(readJson)));setOrders(o.orders as Order[]);setProducts(p.products as AdminProduct[]);setZones(s.zones as Zone[]);setSettings(s.settings as StoreSettings);setPixConfigured(Boolean(s.pixConfigured));setError('');}catch(e){setError(e instanceof Error?e.message:'Não foi possível carregar o painel.');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(),20000);return()=>clearInterval(timer);},[load]);
  async function save(url:string,body:unknown,success:string){setSaving(url);setError('');setNotice('');try{await readJson(await fetch(url,{method:url.endsWith('/orders')?'PATCH':'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));await load();setNotice(success);return true;}catch(e){setError(e instanceof Error?e.message:'Não foi possível salvar.');return false;}finally{setSaving('');}}
  const received=orders.reduce((n,o)=>n+o.paidAmount,0),open=orders.filter(o=>['received','preparing','out_for_delivery'].includes(o.status)).length;
  return <main className="admin-page"><header className="admin-header"><Link href="/" className="admin-back"><ArrowLeft size={18}/> Voltar à loja</Link><span className="admin-brand">PORTO <small>ESFIRRAS</small></span><span className="admin-tag">PAINEL DA LOJA</span></header><div className="admin-wrap"><div className="admin-title"><div><p className="eyebrow dark">OPERAÇÃO</p><h1>Minha <em>loja.</em></h1><p>Pedidos, cardápio e entregas em um só lugar.</p></div><button onClick={()=>void load()} className="admin-refresh" type="button"><RefreshCw size={17}/> Atualizar</button></div>{error&&<div className="admin-message" role="alert">{error}</div>}{notice&&<div className="admin-feedback" role="status">{notice}</div>}{loading?<div className="admin-message">Carregando painel...</div>:<Tabs defaultValue="orders"><TabsList className="admin-tabs"><TabsTrigger value="orders">Pedidos</TabsTrigger><TabsTrigger value="catalog">Cardápio</TabsTrigger><TabsTrigger value="settings">Configurações</TabsTrigger></TabsList>
    <TabsContent value="orders"><div className="admin-stats"><div><span>Pedidos registrados</span><strong>{orders.length}</strong></div><div><span>Em andamento</span><strong>{open}</strong></div><div><span>Valor realmente recebido</span><strong>{money(received)}</strong><small>Somente pagamentos confirmados ou lançados.</small></div></div>{!orders.length?<div className="admin-empty"><ClipboardList size={36}/><h2>Sem pedidos por enquanto</h2><p>Os pedidos feitos pelo site aparecerão aqui.</p></div>:<div className="orders-list">{orders.map(o=><article className="order-card" key={o.id}><div className="order-head"><div><span>#{o.code} · {new Date(o.createdAt).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short',timeZone:'America/Porto_Velho'})}</span><h2>{o.customerName}</h2></div><strong>{money(o.total||o.subtotal)}</strong></div><div className="order-main"><div><h3>Itens</h3>{o.items.map((p,i)=><p key={i}>{p.quantity}× {p.name} <span>{money(p.price*p.quantity)}</span></p>)}{o.deliveryFee>0&&<p>Taxa de entrega <span>{money(o.deliveryFee)}</span></p>}</div><div><h3>{o.fulfillment==='delivery'?'Entrega':'Retirada'}</h3><p>{o.phone}</p>{o.address&&<p>{o.address}</p>}{o.note&&<p>Observações: {o.note}</p>}<p>Pagamento: {o.paymentMethod==='pix'?'Pix':o.paymentMethod==='test'?'Teste':'Na retirada'}</p><p>Recebido: <strong>{money(o.paidAmount)}</strong> de {money(o.total||o.subtotal)} · {o.paymentStatus==='paid'?'pago':o.paymentStatus==='partial'?'parcial':'pendente'}</p></div></div><div className="order-bottom"><label>Etapa<select value={o.status} disabled={saving==='/api/admin/orders'||o.status==='test'} onChange={e=>void save('/api/admin/orders',{id:o.id,status:e.target.value},'Status atualizado.')} aria-label={`Etapa do pedido ${o.code}`}>{Object.entries(states).map(([value,label])=><option key={value} value={value} disabled={value==='test'||value==='awaiting_payment'}>{label}</option>)}</select></label>{o.paymentMethod==='at_pickup'&&<form onSubmit={async e=>{e.preventDefault();const cents=Math.round(Number(amounts[o.id]??o.paidAmount/100)*100);await save('/api/admin/orders',{id:o.id,paidAmount:cents},'Valor recebido atualizado.');}}><label>Valor recebido (R$)<input type="number" step="0.01" min="0" max={(o.total/100).toFixed(2)} value={amounts[o.id]??(o.paidAmount/100).toFixed(2)} onChange={e=>setAmounts(v=>({...v,[o.id]:e.target.value}))} /></label><button type="submit" className="admin-save" disabled={!!saving}>Registrar</button></form>}</div></article>)}</div>}</TabsContent>
    <TabsContent value="catalog"><div className="admin-section-head"><div><h2>Cardápio</h2><p>Confira preços e ingredientes antes de abrir os pedidos ao público.</p></div><button className="admin-save" type="button" onClick={()=>{setEditing({...blankProduct});setProductPrice("6.00");}}><Plus size={17}/> Novo produto</button></div><div className="admin-product-list">{products.map(p=><div className="admin-product" key={p.id}><div><small>{p.category} · {p.active?'Visível':'Oculto'}</small><h3>{p.name}</h3><p>{p.description}</p></div><strong>{money(p.price)}</strong><button type="button" className="admin-edit" onClick={()=>{setEditing({...p});setProductPrice((p.price/100).toFixed(2));}}>Editar</button></div>)}</div>{editing&&<form className="admin-editor" onSubmit={async e=>{e.preventDefault();if(await save('/api/admin/catalog',{...editing,price:Math.round(Number(productPrice)*100)},'Produto salvo no cardápio.'))setEditing(null);}}><div className="admin-section-head"><h2>{editing.id?'Editar produto':'Novo produto'}</h2><button type="button" onClick={()=>setEditing(null)}>Fechar</button></div><label>Nome<input required value={editing.name} maxLength={100} onChange={e=>setEditing({...editing,name:e.target.value})}/></label><label>Descrição<textarea value={editing.description} maxLength={400} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><label>Categoria<select value={editing.category} onChange={e=>setEditing({...editing,category:e.target.value as Product['category']})}>{['Esfirras salgadas','Esfirras doces','Pizzas','Bebidas'].map(c=><option key={c}>{c}</option>)}</select></label><label>Preço (R$)<input type="number" min="1" max="1000" step="0.01" value={productPrice} onChange={e=>setProductPrice(e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={editing.active} onChange={e=>setEditing({...editing,active:e.target.checked})}/> Produto visível no site</label><button className="admin-save" type="submit" disabled={!!saving}><Save size={16}/> Salvar produto</button></form>}</TabsContent>
    <TabsContent value="settings"><div className="admin-section-head"><div><h2>Pedidos e pagamentos</h2><p>O site continua privado. Ative pedidos reais somente depois de confirmar o cardápio e as formas de pagamento.</p></div></div><form className="admin-editor" onSubmit={e=>{e.preventDefault();void save('/api/admin/settings',{kind:'settings',...settings},'Configurações salvas.');}}>{([['pickupEnabled','Permitir retirada na loja'],['deliveryEnabled','Permitir entrega por bairro'],['payOnPickupEnabled','Aceitar pagamento na retirada'],['pixEnabled',`Aceitar Pix${pixConfigured?'':' · falta configurar Mercado Pago'}`],['ordersEnabled','Receber pedidos reais']] as const).map(([key,label])=><label className="admin-check" key={key}><input type="checkbox" checked={settings[key]} disabled={key==='pixEnabled'&&!pixConfigured} onChange={e=>setSettings(v=>({...v,[key]:e.target.checked}))}/>{label}</label>)}<button className="admin-save" type="submit" disabled={!!saving}><Save size={16}/> Salvar configuração</button><p className="admin-help">Pix só deve ser ativado após testar a conta da loja e configurar a chave de notificações. Até lá, pedidos de teste continuam disponíveis apenas para o responsável.</p></form><div className="admin-section-head"><div><h2>Bairros atendidos</h2><p>O cliente verá a taxa antes de confirmar o pedido.</p></div></div><div className="admin-zones">{zones.map(z=><div key={z.id}><span>{z.name} · {money(z.fee)} {z.active?'':'(oculto)'}</span><button onClick={()=>{setZoneDraft({...z});setZoneFee((z.fee/100).toFixed(2));}} type="button">Editar</button></div>)}</div><form className="admin-editor" onSubmit={async e=>{e.preventDefault();if(await save('/api/admin/settings',{kind:'zone',...zoneDraft,fee:Math.round(Number(zoneFee)*100)},'Bairro salvo.'))setZoneDraft({id:'',name:'',fee:0,active:true});setZoneFee('0.00');}}><h3>{zoneDraft.id?'Editar bairro':'Adicionar bairro'}</h3><label>Nome do bairro<input required value={zoneDraft.name} maxLength={70} onChange={e=>setZoneDraft(v=>({...v,name:e.target.value}))}/></label><label>Taxa de entrega (R$)<input type="number" min="0" max="100" step="0.01" value={zoneFee} onChange={e=>setZoneFee(e.target.value)}/></label><label className="admin-check"><input type="checkbox" checked={zoneDraft.active} onChange={e=>setZoneDraft(v=>({...v,active:e.target.checked}))}/> Bairro disponível</label><button className="admin-save" type="submit" disabled={!!saving}>Salvar bairro</button></form></TabsContent>
  </Tabs>}</div></main>;
}
